#############################################################################
# Makefile for building: bin/MirrorCam
# Generated by qmake (2.01a) (Qt 4.8.1) on: ?? ???. 9 20:55:37 2012
# Project:  MirrorCam.pro
# Template: app
# Command: /usr/bin/qmake -nocache QMAKE_CFLAGS_RELEASE=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_CFLAGS_DEBUG=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_CXXFLAGS_RELEASE=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_CXXFLAGS_DEBUG=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_LFLAGS_RELEASE=-Wl,-Bsymbolic-functions\ -Wl,-z,relro QMAKE_LFLAGS_DEBUG=-Wl,-Bsymbolic-functions\ -Wl,-z,relro QMAKE_STRIP=: PREFIX=/usr -o Makefile MirrorCam.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Wformat-security -D_FORTIFY_SOURCE=2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -I/usr/include/glib-2.0 -I/usr/lib/i386-linux-gnu/glib-2.0/include -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-Bsymbolic-functions -Wl,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/usr/X11R6/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lglib-2.0 -lQtDeclarative -lQtOpenGL -lQtGui -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = :
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = MainWindow.cpp \
		CameraGLWidget.cpp \
		main.cpp \
		details.cpp \
		settings.cpp moc_MainWindow.cpp \
		moc_CameraGLWidget.cpp \
		moc_details.cpp \
		moc_settings.cpp \
		qrc_resource.cpp
OBJECTS       = MainWindow.o \
		CameraGLWidget.o \
		main.o \
		details.o \
		settings.o \
		moc_MainWindow.o \
		moc_CameraGLWidget.o \
		moc_details.o \
		moc_settings.o \
		qrc_resource.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		MirrorCam.pro
QMAKE_TARGET  = MirrorCam
DESTDIR       = bin/
TARGET        = bin/MirrorCam

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_MainForm.h ui_details.h ui_settings.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MirrorCam.pro /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtDeclarative.prl \
		/usr/lib/i386-linux-gnu/libQtOpenGL.prl \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -nocache QMAKE_CFLAGS_RELEASE=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_CFLAGS_DEBUG=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_CXXFLAGS_RELEASE=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_CXXFLAGS_DEBUG=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_LFLAGS_RELEASE=-Wl,-Bsymbolic-functions\ -Wl,-z,relro QMAKE_LFLAGS_DEBUG=-Wl,-Bsymbolic-functions\ -Wl,-z,relro QMAKE_STRIP=: PREFIX=/usr -o Makefile MirrorCam.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtDeclarative.prl:
/usr/lib/i386-linux-gnu/libQtOpenGL.prl:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -nocache QMAKE_CFLAGS_RELEASE=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_CFLAGS_DEBUG=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_CXXFLAGS_RELEASE=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_CXXFLAGS_DEBUG=-g\ -O2\ -fstack-protector\ --param=ssp-buffer-size=4\ -Wformat\ -Wformat-security\ -D_FORTIFY_SOURCE=2 QMAKE_LFLAGS_RELEASE=-Wl,-Bsymbolic-functions\ -Wl,-z,relro QMAKE_LFLAGS_DEBUG=-Wl,-Bsymbolic-functions\ -Wl,-z,relro QMAKE_STRIP=: PREFIX=/usr -o Makefile MirrorCam.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MirrorCam1.0.0 || $(MKDIR) .tmp/MirrorCam1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MirrorCam1.0.0/ && $(COPY_FILE) --parents MainWindow.h CameraGLWidget.h details.h settings.h .tmp/MirrorCam1.0.0/ && $(COPY_FILE) --parents resource.qrc .tmp/MirrorCam1.0.0/ && $(COPY_FILE) --parents MainWindow.cpp CameraGLWidget.cpp main.cpp details.cpp settings.cpp .tmp/MirrorCam1.0.0/ && $(COPY_FILE) --parents MainForm.ui details.ui settings.ui .tmp/MirrorCam1.0.0/ && (cd `dirname .tmp/MirrorCam1.0.0` && $(TAR) MirrorCam1.0.0.tar MirrorCam1.0.0 && $(COMPRESS) MirrorCam1.0.0.tar) && $(MOVE) `dirname .tmp/MirrorCam1.0.0`/MirrorCam1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MirrorCam1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_MainWindow.cpp moc_CameraGLWidget.cpp moc_details.cpp moc_settings.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_CameraGLWidget.cpp moc_details.cpp moc_settings.cpp
moc_MainWindow.cpp: ui_MainForm.h \
		details.h \
		settings.h \
		MainWindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_CameraGLWidget.cpp: CameraGLWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) CameraGLWidget.h -o moc_CameraGLWidget.cpp

moc_details.cpp: details.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) details.h -o moc_details.cpp

moc_settings.cpp: settings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) settings.h -o moc_settings.cpp

compiler_rcc_make_all: qrc_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resource.cpp
qrc_resource.cpp: resource.qrc \
		menu.qml \
		Button.qml \
		images/icon32.png \
		images/settings_normal.png \
		images/windowed_pressed.png \
		images/menu_bg.png \
		images/info_hover.png \
		images/windowed_hover.png \
		images/icon64.png \
		images/icon16.png \
		images/exit_hover.png \
		images/exit_normal.png \
		images/exit_pressed.png \
		images/settings_pressed.png \
		images/info_pressed.png \
		images/info_normal.png \
		images/settings_hover.png \
		images/windowed_normal.png \
		images/icon128.png \
		images/fullscreen_pressed.png \
		images/icon256.png \
		images/fullscreen_normal.png \
		images/fullscreen_hover.png
	/usr/bin/rcc -name resource resource.qrc -o qrc_resource.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MainForm.h ui_details.h ui_settings.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainForm.h ui_details.h ui_settings.h
ui_MainForm.h: MainForm.ui \
		CameraGLWidget.h
	/usr/bin/uic-qt4 MainForm.ui -o ui_MainForm.h

ui_details.h: details.ui
	/usr/bin/uic-qt4 details.ui -o ui_details.h

ui_settings.h: settings.ui
	/usr/bin/uic-qt4 settings.ui -o ui_settings.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

MainWindow.o: MainWindow.cpp MainWindow.h \
		ui_MainForm.h \
		details.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

CameraGLWidget.o: CameraGLWidget.cpp CameraGLWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CameraGLWidget.o CameraGLWidget.cpp

main.o: main.cpp MainWindow.h \
		ui_MainForm.h \
		details.h \
		settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

details.o: details.cpp details.h \
		ui_details.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o details.o details.cpp

settings.o: settings.cpp settings.h \
		ui_settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o settings.o settings.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_CameraGLWidget.o: moc_CameraGLWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CameraGLWidget.o moc_CameraGLWidget.cpp

moc_details.o: moc_details.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_details.o moc_details.cpp

moc_settings.o: moc_settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_settings.o moc_settings.cpp

qrc_resource.o: qrc_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resource.o qrc_resource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

